"""Add SystemConfig table for high-risk password

Revision ID: e13ac02d87f2
Revises: e475dcc3621e
Create Date: 2025-11-07 09:02:50.364972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e13ac02d87f2'
down_revision = 'e475dcc3621e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_table('system_config')
    # ### end Alembic commands ###
