"""Add ban status to User model

Revision ID: e475dcc3621e
Revises: f84007298a47
Create Date: 2025-11-06 21:49:05.555039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e475dcc3621e'
down_revision = 'f84007298a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('ban_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')



    # ### end Alembic commands ###
